// <auto-generated />
using System;
using DigikalaDataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DigikalaDataAccess.Migrations
{
    [DbContext(typeof(DigikalaDB))]
    [Migration("20210622064404_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DigikalaDataAccess.Entity.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentBody")
                        .IsRequired();

                    b.Property<string>("CommentHead")
                        .IsRequired();

                    b.Property<string>("UserName");

                    b.HasKey("CommentID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("DigikalaDataAccess.Entity.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductName")
                        .IsRequired();

                    b.Property<int>("ProductPrice");

                    b.Property<string>("ProductURL");

                    b.HasKey("ID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DigikalaDataAccess.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FirstLogin");

                    b.Property<DateTime>("LasstLogin");

                    b.Property<int>("LoginCount");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.Property<string>("UserPassword")
                        .IsRequired();

                    b.Property<int>("UserType");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new { UserID = 1, FirstLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), LasstLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), LoginCount = 0, UserName = "Admin", UserPassword = "admin", UserType = 0 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
